# Generated by Django 2.2.10 on 2020-03-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacifique', '0003_auto_20200313_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
    ]
