# Generated by Django 2.2.10 on 2020-03-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacifique', '0004_auto_20200317_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id']},
        ),
    ]
